In [1]:
import numpy as np

In [2]:
x = np.array([
    [1,2,3],
    [1,0,2],
    [0,1,0],
])
y = np.array([[1,2,1]])
z = np.array([[2,5,3]])


In [3]:
(x == 3)

array([[False, False,  True],
       [False, False, False],
       [False, False, False]])

In [39]:
np.dot(x,y.T)

array([[8],
       [3],
       [2]])

In [ ]:
np.dot(y,x)

array([3, 3, 7])

In [37]:
np.dot(y,z)

ValueError: shapes (1,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

In [38]:
np.dot(z,y)

ValueError: shapes (1,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

In [41]:
np.zeros((3,1)).shape

(3, 1)